### ISSUE TITLE
Unable to plot in 3D trajectory setpoint

### ISSUE THREAD

**Issue by wico-malaca** [tilak-io/tiplot#31] opened 2022-12-23 17:55 UTC
When I add a new UAV to plot with the vehicle_local_position_setpoint the 3D view gets dark. 

![Screenshot from 2022-12-23 18-54-15](https://user-images.githubusercontent.com/71832122/209384096-74c9ab85-24bc-4329-8711-cf08fff6726c.png)
![Screenshot from 2022-12-23 18-54-25](https://user-images.githubusercontent.com/71832122/209384102-ffaf4d97-8fd8-4ff7-9e21-8a2ca2a68c0f.png)

**Comment by HmZyy** [comment] 2022-12-23 19:59
Hello @wico-malaca,

This issue can happen due to 2 reasons:
- either your log does not have the "vehicle_local_position_setpoint" table in it (seeing that you're using a px4 log, this is unlikely)
- the table "vehicle_local_position_setpoint" contains some NaN values in x,y or z.

Please note that an entity config validation was implemented in v1.0.4.

Can you confirm that you can reproduce this issue with the [latest release](https://github.com/tilak-io/tiplot/releases/latest)

**Comment by wico-malaca** [comment] 2023-01-10 07:54
Hello. The NaN's are a good point, maybe that's the rason. I'll check that out

**Comment by HmZyy** [comment] 2023-01-12 15:04
Closing for now, If the issue still persists, please reopen the issue and we will investigate further.

**Closed by HmZyy** 2023-01-12 15:04 UTC
